inei_payroll:
    resource: "@IneiPayrollBundle/Resources/config/routing.yml"
    prefix:   /

# AcmeDemoBundle routes (to be removed)
_acme_demo:
    resource: "@AcmeDemoBundle/Resources/config/routing.yml"