security:
#    acl:
#        connection: default
    encoders:
        Inei\Bundle\AuthBundle\Entity\Usuarios:
            algorithm:        pbkdf2
            encode_as_base64: true
            iterations:       100

    providers:
        administrators:
            entity: { class: IneiAuthBundle:Usuarios, property: username }

    firewalls:                  
        login:
            pattern:  ^/admin/login$
            security: false

        secured_area:
            pattern:    ^/admin/
            form_login:
                check_path: _admin_security_check
                login_path: _admin_login
                always_use_default_target_path: true
                default_target_path: /admin
            logout:
                path:   _admin_logout
                target: _admin_login
                invalidate_session: false
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        #- { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_USER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }   