<?php

namespace Inei\Bundle\PayrollBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MaestroPersonalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaestroPersonalRepository extends EntityRepository {

    public function findUsingLike($filter = array(), $orderBy = NULL) {
        array_walk($filter, function(&$v, &$k) {
                    $v = " t.$k LIKE '%$v%'";
                });
        $filter = count($filter) > 0 ? 'WHERE ' . implode(' AND ', $filter) : '';
        $query = $this->getEntityManager()
                ->createQuery('SELECT t FROM IneiPayrollBundle:MaestroPersonal t ' . $filter . ' ' . $orderBy);
        return $query->getResult();
    }

    public function findByFullname($fullname) {
        $query = $this->getEntityManager()
                ->createQuery("SELECT t.librElecPer as dni, CONCAT(t.apePatPer,' ',t.apeMatPer, ' ',t.nomEmpPer) as fullname
                    FROM IneiPayrollBundle:MaestroPersonal t 
                    Where CONCAT(t.apePatPer,' ',t.apeMatPer, ' ',t.nomEmpPer) like :filtro")
                ->setParameter('filtro', "%$fullname%")
                ->setMaxResults(10);
        
        return $query->getArrayResult();
    }    
}
