<?php

namespace Inei\Bundle\PayrollBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TplanillaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TplanillaRepository extends EntityRepository
{
    public function findUsingLike($filter = array(), $orderBy=NULL) {
        array_walk($filter, function(&$v, &$k) {
                    if ($k === 'descTipoTpl') {
                        $v = " t.$k LIKE '%$v%'";
                    } else {
                        $v = "t.$k = '$v'";
                    }
                });
        $filter = count($filter) > 0 ? 'WHERE ' . implode(' AND ', $filter) : '';
        $query = $this->getEntityManager()
                ->createQuery('SELECT t FROM IneiPayrollBundle:Tplanilla t ' . $filter.' '.$orderBy);
        return $query->getResult();
    }
}
