inei_payroll_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: IneiPayrollBundle:Default:index }

_admin:
    resource: "@IneiPayrollBundle/Controller/SecuredController.php"
    type:     annotation
    prefix:   /admin