inei_payroll_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: IneiPayrollBundle:Default:index }
    
_inei_payroll_inventory:
    resource: "@IneiPayrollBundle/Controller/InventarioController.php"
    type:     annotation
    prefix:   /admin/inventory
    requirements:
        name: ".+"
    
_inei_payroll_concept:
    resource: "@IneiPayrollBundle/Controller/ConceptoController.php"
    type:     annotation
    prefix:   /admin/concept
    
_inei_payroll_payroll:
    resource: "@IneiPayrollBundle/Controller/PlanillaController.php"
    type:     annotation
    prefix:   /admin/payroll