parameters:
#    inei_payroll.example.class: Inei\Bundle\PayrollBundle\Example

services:
#    inei_payroll.example:
#        class: %inei_payroll.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    inei_payroll.form.type.tomo:
        class: Inei\Bundle\PayrollBundle\Form\Type\TomoType
        tags:
            - { name: form.type, alias: tomo }
    inei_payroll.form.type.concepto:
        class: Inei\Bundle\PayrollBundle\Form\Type\ConceptoType
        tags:
            - { name: form.type, alias: concepto }
    inei_payroll.form.type.folio:
        class: Inei\Bundle\PayrollBundle\Form\Type\FolioType
        tags:
            - { name: form.type, alias: folio }
    inei_payroll.form.type.conceptofolio:
        class: Inei\Bundle\PayrollBundle\Form\Type\ConceptoFolioType
        tags:
            - { name: form.type, alias: conceptofolio }
    inei_payroll.form.type.planilla:
        class: Inei\Bundle\PayrollBundle\Form\Type\PlanillaType
        tags:
            - { name: form.type, alias: planilla }
    inei_payroll.form.type.tplanilla:
        class: Inei\Bundle\PayrollBundle\Form\Type\TplanillaType
        tags:
            - { name: form.type, alias: tplanilla }
    inei_payroll.form.type.subtplanilla:
        class: Inei\Bundle\PayrollBundle\Form\Type\SubtplanillaType
        tags:
            - { name: form.type, alias: subtplanilla }
    #ONLY ENTITY
    inei_payroll.form.type.tomos:
        class: Inei\Bundle\PayrollBundle\Form\Type\TomosType
        tags:
            - { name: form.type, alias: tomos }
    inei_payroll.form.type.folios:
        class: Inei\Bundle\PayrollBundle\Form\Type\FoliosType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: folios }
    inei_payroll.form.type.conceptofolios:
        class: Inei\Bundle\PayrollBundle\Form\Type\ConceptoFoliosType
        tags:
            - { name: form.type, alias: conceptofolios }
    #SEARCHS
    inei_payroll.form.type.search_tomos:
        class: Inei\Bundle\PayrollBundle\Form\Type\SearchTomosType
        tags:
            - { name: form.type, alias: search_tomos }
    inei_payroll.form.type.search_folios:
        class: Inei\Bundle\PayrollBundle\Form\Type\SearchFoliosType
        tags:
            - { name: form.type, alias: search_folios }            
    inei_payroll.form.type.registrar_planilla:
        class: Inei\Bundle\PayrollBundle\Form\Type\RegistrarPlanillaType
        tags:
            - { name: form.type, alias: registrar_planilla }