parameters:
#    inei_payroll.example.class: Inei\Bundle\PayrollBundle\Example

services:
#    inei_payroll.example:
#        class: %inei_payroll.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    planilla_service:
        class: Inei\Bundle\PayrollBundle\Service\PlanillaService
        arguments: ["@doctrine.orm.entity_manager", "@security.context"]
        tags:
            - { name: service, alias: planilla_service }
    folios_service:
        class: Inei\Bundle\PayrollBundle\Service\FoliosService
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: service, alias: folios_service }
    tomos_service:
        class: Inei\Bundle\PayrollBundle\Service\TomosService
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: service, alias: tomos_service }
    excel_service:
        class: Inei\Bundle\PayrollBundle\Service\ExcelService
        tags:
            - { name: service, alias: excel_service }
    concepto_service:
        class: Inei\Bundle\PayrollBundle\Service\ConceptoService
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: service, alias: concepto_service }
    asignacion_service:
        class: Inei\Bundle\PayrollBundle\Service\AsignacionService
        arguments: ["@doctrine.orm.entity_manager", "@security.context"]
        tags:
            - { name: service, alias: asignacion_service }
    inei_payroll.form.type.tomo:
        class: Inei\Bundle\PayrollBundle\Form\Type\TomoType
        tags:
            - { name: form.type, alias: tomo }
    inei_payroll.form.type.concepto:
        class: Inei\Bundle\PayrollBundle\Form\Type\ConceptoType
        tags:
            - { name: form.type, alias: concepto }
    inei_payroll.form.type.folio:
        class: Inei\Bundle\PayrollBundle\Form\Type\FolioType
        tags:
            - { name: form.type, alias: folio }
    inei_payroll.form.type.conceptofolio:
        class: Inei\Bundle\PayrollBundle\Form\Type\ConceptoFolioType
        tags:
            - { name: form.type, alias: conceptofolio }
    inei_payroll.form.type.planilla:
        class: Inei\Bundle\PayrollBundle\Form\Type\PlanillaType
        tags:
            - { name: form.type, alias: planilla }
    inei_payroll.form.type.tplanilla:
        class: Inei\Bundle\PayrollBundle\Form\Type\TplanillaType
        tags:
            - { name: form.type, alias: tplanilla }
    inei_payroll.form.type.subtplanilla:
        class: Inei\Bundle\PayrollBundle\Form\Type\SubtplanillaType
        tags:
            - { name: form.type, alias: subtplanilla }
    inei_payroll.form.type.personal:
        class: Inei\Bundle\PayrollBundle\Form\Type\MaestroPersonalType
        tags:
            - { name: form.type, alias: personal }
    #ONLY ENTITY
    inei_payroll.form.type.tomos:
        class: Inei\Bundle\PayrollBundle\Form\Type\TomosType
        tags:
            - { name: form.type, alias: tomos }
    inei_payroll.form.type.folios:
        class: Inei\Bundle\PayrollBundle\Form\Type\FoliosType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: folios }
    inei_payroll.form.type.conceptofolios:
        class: Inei\Bundle\PayrollBundle\Form\Type\ConceptoFoliosType
        tags:
            - { name: form.type, alias: conceptofolios }
    #SEARCHS
    inei_payroll.form.type.search_tomos:
        class: Inei\Bundle\PayrollBundle\Form\Type\SearchTomosType
        tags:
            - { name: form.type, alias: search_tomos }
    inei_payroll.form.type.search_folios:
        class: Inei\Bundle\PayrollBundle\Form\Type\SearchFoliosType
        tags:
            - { name: form.type, alias: search_folios }            
    inei_payroll.form.type.registrar_planilla:
        class: Inei\Bundle\PayrollBundle\Form\Type\RegistrarPlanillaType
        arguments: ["@usuario_service"]
        tags:
            - { name: form.type, alias: registrar_planilla }
    inei_payroll.form.type.exceltomo:
        class: Inei\Bundle\PayrollBundle\Form\Type\ExcelTomoType
        tags:
            - { name: form.type, alias: exceltomo }
    inei_payroll.form.type.search_tplanilla:
        class: Inei\Bundle\PayrollBundle\Form\Type\SearchTplanillaType
        tags:
            - { name: form.type, alias: search_tplanilla }
    inei_payroll.form.type.search_subtplanilla:
        class: Inei\Bundle\PayrollBundle\Form\Type\SearchSubtplanillaType
        tags:
            - { name: form.type, alias: search_subtplanilla }
    inei_payroll.form.type.search_concepto:
        class: Inei\Bundle\PayrollBundle\Form\Type\SearchConceptoType
        tags:
            - { name: form.type, alias: search_concepto }
    inei_payroll.form.type.search_personal:
        class: Inei\Bundle\PayrollBundle\Form\Type\SearchMaestroPersonalType
        tags:
            - { name: form.type, alias: search_personal }
    inei_payroll.form.type.search_tomoexcel:
        class: Inei\Bundle\PayrollBundle\Form\Type\SearchTomoExcelType
        tags:
            - { name: form.type, alias: search_tomoexcel }
    inei_payroll.form.type.asignacion:
        class: Inei\Bundle\PayrollBundle\Form\Type\AsignacionType
        arguments: ["@usuario_service"]
        tags:
            - { name: form.type, alias: asignacion }
    inei_payroll.form.type.asignacion_search:
        class: Inei\Bundle\PayrollBundle\Form\Type\AsignacionSearchType
        tags:
            - { name: form.type, alias: asignacion_search }