<?php

namespace Inei\Bundle\AuthBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PermissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PermissionRepository extends EntityRepository
{
    public function getByUser($pk, $module, $perm){
        $DQL = "SELECT p
            FROM IneiAuthBundle:Permission p
            JOIN p.module m
            JOIN p.role r
            JOIN r.users u
            WHERE u.id = :pk AND p.module=:module AND p.type LIKE :perm";//AND :perm in p.type 
        $qb = $this->getEntityManager()->createQuery($DQL)
                ->setParameters(array(
            'pk' => is_numeric($pk)?$pk:0,
            'perm' => '%'.$perm.'%',
            'module' => $module
        ));
        $re = $qb->getResult();
        return $re;
    }
}