<?php

namespace Inei\Bundle\AuthBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\User\UserProviderInterface;

/**
 * UsuariosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuariosRepository extends EntityRepository implements UserProviderInterface
{
    public function loadUserByUsername($username)        
    {
        echo $username;
        $q = $this
            ->createQueryBuilder('u')
            ->select('u, r')
            ->leftJoin('u.roles', 'r')
            ->where('u.username = :username OR u.email = :email')
            ->setParameter('username', $username)
            ->setParameter('email', $username)
            ->getQuery();
        //print_r($q->getResult());
        return $q->getResult();
    }
    
    public function findOneByPk($pk){
        $q = $this
            ->createQueryBuilder('u')
            ->select('u, r')
            ->leftJoin('u.roles', 'r')
            ->where('u.id = :id')            
            ->setParameter('id', $pk)
            ->getQuery();
        //print_r($q->getResult()[0]);
        return $q->getResult()[0];
    }

    public function refreshUser(\Symfony\Component\Security\Core\User\UserInterface $user) {
        //print_r($user);
        //echo $user->getUsername();
        $user = $this->findOneByPk($user->getId());
        return $user;
    }

    public function supportsClass($class) {
        return true;
    }    
}
