Inei\Bundle\PayrollBundle\Entity\MaestroPersonal:
    type: entity
    table: MAESTRO_PERSONAL
    fields:
        codiEmplPer:
            id: true
            type: string
            length: 8
            fixed: false
            nullable: false
            column: CODI_EMPL_PER
            generator:
                strategy: SEQUENCE
        apePatPer:
            type: string
            length: 35
            fixed: false
            nullable: false
            column: APE_PAT_PER
        apeMatPer:
            type: string
            length: 35
            fixed: false
            nullable: false
            column: APE_MAT_PER
        nomEmpPer:
            type: string
            length: 35
            fixed: false
            nullable: false
            column: NOM_EMP_PER
        nombCortPer:
            type: string
            length: 70
            fixed: false
            nullable: false
            column: NOMB_CORT_PER
        dirEmpPer:
            type: string
            length: 150
            fixed: false
            nullable: false
            column: DIR_EMP_PER
        codiDepaDpt:
            type: string
            length: 2
            fixed: false
            nullable: false
            column: CODI_DEPA_DPT
        codiProvTpr:
            type: string
            length: 2
            fixed: false
            nullable: false
            column: CODI_PROV_TPR
        codiDistTdi:
            type: string
            length: 2
            fixed: false
            nullable: false
            column: CODI_DIST_TDI
        numTelPer:
            type: string
            length: 10
            fixed: false
            nullable: false
            column: NUM_TEL_PER
        fecIngPer:
            type: date
            nullable: false
            column: FEC_ING_PER
        tipoPlanTpl:
            type: string
            length: 2
            fixed: false
            nullable: false
            column: TIPO_PLAN_TPL
        estCivPer:
            type: string
            length: 1
            fixed: false
            nullable: false
            column: EST_CIV_PER
        sexEmpPer:
            type: string
            length: 1
            fixed: false
            nullable: false
            column: SEX_EMP_PER
        graInsPer:
            type: string
            length: 1
            fixed: false
            nullable: false
            column: GRA_INS_PER
        fecNacPer:
            type: date
            nullable: false
            column: FEC_NAC_PER
        paisNaciTpa:
            type: string
            length: 4
            fixed: false
            nullable: false
            column: PAIS_NACI_TPA
        depaNaciDpt:
            type: string
            length: 2
            fixed: false
            nullable: false
            column: DEPA_NACI_DPT
        provNaciTpr:
            type: string
            length: 2
            fixed: false
            nullable: false
            column: PROV_NACI_TPR
        distNaciTdi:
            type: string
            length: 2
            fixed: false
            nullable: false
            column: DIST_NACI_TDI
        codiDepeTde:
            type: string
            length: 4
            fixed: false
            nullable: false
            column: CODI_DEPE_TDE
        ubicFisiTde:
            type: string
            length: 4
            fixed: false
            nullable: false
            column: UBIC_FISI_TDE
        codiNiveTni:
            type: string
            length: 3
            fixed: false
            nullable: false
            column: CODI_NIVE_TNI
        niveEncTni:
            type: string
            length: 3
            fixed: false
            nullable: false
            column: NIVE_ENC_TNI
        estaTrabPer:
            type: string
            length: 1
            fixed: false
            nullable: false
            column: ESTA_TRAB_PER
        conTraPer:
            type: string
            length: 1
            fixed: false
            nullable: false
            column: CON_TRA_PER
        regLabPer:
            type: string
            length: 8
            fixed: false
            nullable: false
            column: REG_LAB_PER
        regPenPer:
            type: string
            length: 8
            fixed: false
            nullable: false
            column: REG_PEN_PER
        codiCargTca:
            type: string
            length: 8
            fixed: false
            nullable: false
            column: CODI_CARG_TCA
        cargEncTca:
            type: string
            length: 8
            fixed: false
            nullable: false
            column: CARG_ENC_TCA
        flagAfpPer:
            type: string
            length: 1
            fixed: false
            nullable: false
            column: FLAG_AFP_PER
        codiAfp:
            type: string
            length: 2
            fixed: false
            nullable: false
            column: CODI_AFP
        fechAfpPer:
            type: date
            nullable: false
            column: FECH_AFP_PER
        codiAfpPer:
            type: string
            length: 15
            fixed: false
            nullable: false
            column: CODI_AFP_PER
        librElecPer:
            type: string
            length: 8
            fixed: false
            nullable: false
            column: LIBR_ELEC_PER
        librMiliPer:
            type: string
            length: 10
            fixed: false
            nullable: false
            column: LIBR_MILI_PER
        codiIpssPer:
            type: string
            length: 16
            fixed: false
            nullable: false
            column: CODI_IPSS_PER
        numeBrevPer:
            type: string
            length: 15
            fixed: false
            nullable: false
            column: NUME_BREV_PER
        gruSangPer:
            type: string
            length: 4
            fixed: false
            nullable: false
            column: GRU_SANG_PER
        codMonSuelPer:
            type: string
            length: 2
            fixed: false
            nullable: false
            column: COD_MON_SUEL_PER
        flagSuelPer:
            type: string
            length: 1
            fixed: false
            nullable: false
            column: FLAG_SUEL_PER
        bancSuelTbc:
            type: string
            length: 2
            fixed: false
            nullable: false
            column: BANC_SUEL_TBC
        suelCtaPer:
            type: string
            length: 18
            fixed: false
            nullable: false
            column: SUEL_CTA_PER
        bancCtsTbc:
            type: string
            length: 2
            fixed: false
            nullable: false
            column: BANC_CTS_TBC
        ctsCtaPer:
            type: string
            length: 18
            fixed: false
            nullable: false
            column: CTS_CTA_PER
        codMonCtsPer:
            type: string
            length: 2
            fixed: false
            nullable: false
            column: COD_MON_CTS_PER
        numePlazPer:
            type: string
            length: 8
            fixed: false
            nullable: false
            column: NUME_PLAZ_PER
        fechRnomPer:
            type: date
            nullable: false
            column: FECH_RNOM_PER
        numeRnomPer:
            type: string
            length: 10
            fixed: false
            nullable: false
            column: NUME_RNOM_PER
        sedeActuPer:
            type: string
            length: 3
            fixed: false
            nullable: false
            column: SEDE_ACTU_PER
        fingAdmPer:
            type: date
            nullable: false
            column: FING_ADM_PER
        fingCarrpPer:
            type: date
            nullable: false
            column: FING_CARRP_PER
        otroDocuPer:
            type: string
            length: 15
            fixed: false
            nullable: false
            column: OTRO_DOCU_PER
        observaPer:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: OBSERVA_PER
        cargoRemuPer:
            type: string
            length: 8
            fixed: false
            nullable: false
            column: CARGO_REMU_PER
        nivelRemuPer:
            type: string
            length: 3
            fixed: false
            nullable: false
            column: NIVEL_REMU_PER
        plazaRemuPer:
            type: string
            length: 8
            fixed: false
            nullable: false
            column: PLAZA_REMU_PER
        depeRemuPer:
            type: string
            length: 4
            fixed: false
            nullable: false
            column: DEPE_REMU_PER
        obserRemuPer:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: OBSER_REMU_PER
        tipoCuenPer:
            type: string
            length: 1
            fixed: false
            nullable: false
            column: TIPO_CUEN_PER
        seguMediPer:
            type: string
            length: 1
            fixed: false
            nullable: false
            column: SEGU_MEDI_PER
        sedeRemuPer:
            type: string
            length: 3
            fixed: false
            nullable: false
            column: SEDE_REMU_PER
        apepSoltPer:
            type: string
            length: 20
            fixed: false
            nullable: false
            column: APEP_SOLT_PER
        apemSoltPer:
            type: string
            length: 20
            fixed: false
            nullable: false
            column: APEM_SOLT_PER
        nombSoltEr:
            type: string
            length: 30
            fixed: false
            nullable: false
            column: NOMB_SOLT_ER
        cesaSobrPer:
            type: string
            length: 1
            fixed: false
            nullable: false
            column: CESA_SOBR_PER
        fecCesePer:
            type: date
            nullable: false
            column: FEC_CESE_PER
        nombTituCes:
            type: string
            length: 70
            fixed: false
            nullable: false
            column: NOMB_TITU_CES
        nombCobrCes:
            type: string
            length: 70
            fixed: false
            nullable: false
            column: NOMB_COBR_CES
        encaPlazPer:
            type: string
            length: 8
            fixed: false
            nullable: false
            column: ENCA_PLAZ_PER
        flagPropuesta:
            type: string
            length: 1
            fixed: false
            nullable: false
            column: FLAG_PROPUESTA
        metaProp:
            type: string
            length: 4
            fixed: false
            nullable: false
            column: META_PROP
        ftefto:
            type: string
            length: 4
            fixed: false
            nullable: false
            column: FTEFTO
        codiProyPin:
            type: string
            length: 4
            fixed: false
            nullable: false
            column: CODI_PROY_PIN
        codrie:
            type: string
            length: 2
            fixed: false
            nullable: false
            column: CODRIE
        flagAlmacen:
            type: string
            length: 1
            fixed: false
            nullable: false
            column: FLAG_ALMACEN
        fechIniRecu:
            type: date
            nullable: false
            column: FECH_INI_RECU
        flagRecurrente:
            type: string
            length: 1
            fixed: false
            nullable: false
            column: FLAG_RECURRENTE
        obsRecu:
            type: string
            length: 200
            fixed: false
            nullable: false
            column: OBS_RECU
        flagFotocPer:
            type: string
            length: 1
            fixed: false
            nullable: false
            column: FLAG_FOTOC_PER
        indValido:
            type: string
            length: 1
            fixed: false
            nullable: false
            column: IND_VALIDO
        bioSuserid:
            type: string
            length: 8
            fixed: false
            nullable: false
            column: BIO_SUSERID
        tipoViaPer:
            type: string
            length: 2
            fixed: false
            nullable: false
            column: TIPO_VIA_PER
        nombViaPer:
            type: string
            length: 50
            fixed: false
            nullable: false
            column: NOMB_VIA_PER
        numeDirePer:
            type: string
            length: 6
            fixed: false
            nullable: false
            column: NUME_DIRE_PER
        kmDirePer:
            type: string
            length: 6
            fixed: false
            nullable: false
            column: KM_DIRE_PER
        mzDirePer:
            type: string
            length: 6
            fixed: false
            nullable: false
            column: MZ_DIRE_PER
        inteDirePer:
            type: string
            length: 6
            fixed: false
            nullable: false
            column: INTE_DIRE_PER
        dptoDirePer:
            type: string
            length: 6
            fixed: false
            nullable: false
            column: DPTO_DIRE_PER
        loteDirePer:
            type: string
            length: 6
            fixed: false
            nullable: false
            column: LOTE_DIRE_PER
        pisoDirePer:
            type: string
            length: 6
            fixed: false
            nullable: false
            column: PISO_DIRE_PER
        tipoZonaPer:
            type: string
            length: 2
            fixed: false
            nullable: false
            column: TIPO_ZONA_PER
        nombZonaPer:
            type: string
            length: 50
            fixed: false
            nullable: false
            column: NOMB_ZONA_PER
        nombRefdomPer:
            type: string
            length: 150
            fixed: false
            nullable: false
            column: NOMB_REFDOM_PER
        numRucPer:
            type: string
            length: 12
            fixed: false
            nullable: false
            column: NUM_RUC_PER
        numCelPer:
            type: string
            length: 15
            fixed: false
            nullable: false
            column: NUM_CEL_PER
        emailPer:
            type: string
            length: 50
            fixed: false
            nullable: false
            column: EMAIL_PER
        emailInsti:
            type: string
            length: 50
            fixed: false
            nullable: false
            column: EMAIL_INSTI
        codiFuncTca:
            type: string
            length: 8
            fixed: false
            nullable: false
            column: CODI_FUNC_TCA
        cargEncPer:
            type: string
            length: 3
            fixed: false
            nullable: false
            column: CARG_ENC_PER
        marca:
            type: string
            length: 1
            fixed: false
            nullable: false
            column: MARCA
        flagCuenta:
            type: string
            length: 1
            fixed: false
            nullable: false
            column: FLAG_CUENTA
        codiUbicOfic:
            type: string
            length: 3
            fixed: false
            nullable: false
            column: CODI_UBIC_OFIC
        nombPrimPer:
            type: string
            length: 25
            fixed: false
            nullable: false
            column: NOMB_PRIM_PER
        nombSeguPer:
            type: string
            length: 25
            fixed: false
            nullable: false
            column: NOMB_SEGU_PER
        tipoComisionAfp:
            type: string
            length: 2
            fixed: false
            nullable: false
            column: TIPO_COMISION_AFP
    lifecycleCallbacks: {  }
