Inei\Bundle\PayrollBundle\Entity\PlanillaHistoricas:
    type: entity
    table: PLANILLA_HISTORICAS
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: SEQUENCE
        tipoPlanTplId:
            type: string
            length: 2
            fixed: false
            nullable: false
            column: TIPO_PLAN_TPL_id
        subtPlanTplId:
            type: string
            length: 2
            fixed: false
            nullable: false
            column: SUBT_PLAN_TPL_id
        anoPeriTpe:
            type: string
            length: 4
            fixed: false
            nullable: false
            column: ANO_PERI_TPE
        numePeriTpe:
            type: string
            length: 2
            fixed: false
            nullable: false
            column: NUME_PERI_TPE
        codiEmplPerId:
            type: string
            length: 8
            fixed: false
            nullable: false
            column: CODI_EMPL_PER_id
        codiConcTcoId:
            type: string
            length: 5
            fixed: false
            nullable: false
            column: CODI_CONC_TCO_id
        valoCalcPhi:
            type: decimal
            nullable: false
            column: VALO_CALC_PHI
    manyToOne:
        'tipoPlanTpl':
            targetEntity: 'tplanilla'
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                'TIPO_PLAN_TPL_id':
                    referencedColumnName: 'TIPO_PLAN_TPL'
            orphanRemoval: false
        'subtPlanTpl':
            targetEntity: 'subtplanilla'
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                'SUBT_PLAN_TPL_id':
                    referencedColumnName: 'SUBT_PLAN_STP'
            orphanRemoval: false
        'codiEmplPer':
            targetEntity: 'maestroPersonal'
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                'CODI_EMPL_PER_id':
                    referencedColumnName: 'CODI_EMPL_PER'
            orphanRemoval: false
        'codiConcTco':
            targetEntity: 'conceptos'
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                'CODI_CONC_TCO_id':
                    referencedColumnName: 'CODI_CONC_TCO'
            orphanRemoval: false
    lifecycleCallbacks: {  }
