Inei\Bundle\PayrollBundle\Entity\Subtplanilla:
    type: entity
    table: SUBTPLANILLA
    fields:
        subtPlanStp:
            id: true
            type: string
            length: 2
            fixed: false
            nullable: false
            column: SUBT_PLAN_STP
            generator:
                strategy: SEQUENCE
        tipoPlanTplId:
            type: string
            length: 2
            fixed: false
            nullable: false
            column: TIPO_PLAN_TPL_id
        descSubtStp:
            type: string
            length: 40
            fixed: false
            nullable: false
            column: DESC_SUBT_STP
        tituSubtStp:
            type: string
            length: 40
            fixed: false
            nullable: false
            column: TITU_SUBT_STP
        observ:
            type: string
            length: 60
            fixed: false
            nullable: false
            column: OBSERV
    manyToOne:
        'tipoPlanTpl':
            targetEntity: 'tplanilla'
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                'TIPO_PLAN_TPL_id':
                    referencedColumnName: 'TIPO_PLAN_TPL'
            orphanRemoval: false
    lifecycleCallbacks: {  }
