<?php

namespace Inei\Bundle\ConsistenciaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PersonalEncontradoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonalEncontradoRepository extends EntityRepository
{
}
