inei_auth_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: IneiAuthBundle:Default:index }

_admin:
    resource: "@IneiAuthBundle/Controller/SecuredController.php"
    type:     annotation
    prefix:   /admin