_admin:
    resource: "@IneiAuthBundle/Controller/SecuredController.php"
    type:     annotation
    prefix:   /admin
    
_admin_crud:
    resource: "@IneiAuthBundle/Controller/SecurityCrudController.php"
    type:     annotation
    prefix:   /admin/security