parameters:
#    inei_auth.example.class: Inei\Bundle\AuthBundle\Example

services:
#    inei_auth.example:
#        class: %inei_auth.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    inei_auth.form.type.usuario:
        class: Inei\Bundle\AuthBundle\Form\Type\UsuarioType
        tags:
            - { name: form.type, alias: usuario }
            
    inei_auth.form.type.role:
        class: Inei\Bundle\AuthBundle\Form\Type\RoleType
        tags:
            - { name: form.type, alias: role }

    inei_auth.form.type.permission:
        class: Inei\Bundle\AuthBundle\Form\Type\PermissionType
        tags:
            - { name: form.type, alias: permission }

    inei_auth.form.type.usuario_search:
        class: Inei\Bundle\AuthBundle\Form\Type\UsuarioSearchType
        tags:
            - { name: form.type, alias: usuario_search }

    usuario_service:
        class: Inei\Bundle\AuthBundle\Service\UsuarioService
        arguments: ["@security.encoder_factory", "@security.context", "@doctrine.orm.entity_manager"]
        tags:
            - { name: service, alias: usuario_service }