parameters:
#    inei_auth.example.class: Inei\Bundle\AuthBundle\Example

services:
#    inei_auth.example:
#        class: %inei_auth.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
