Inei\Bundle\AuthBundle\Entity\Usuarios:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [username]
            message: 'Ya existe un usuario con el mismo usuario.'